Multiple fixes (#67, #68, #71, #72, #73)
ubikingenierie/ulp-observability-plugin pull request #76
Opened 2023-04-24 08:22 UTC by Liard-Thomas

This part correctly displays the cumulated metrics of the test, instead of the last recorded period. These datas match the summary report values at the end of the test.
![result](https://user-images.githubusercontent.com/38759935/233939091-d3215e50-3570-4b60-9f01-f12b49a8af40.png)
Threads value correspond to the max number of threads running at the same time for every periods.

2023-04-25 08:23 UTC, Liard-Thomas commented
I unintentionally fixed the bug of the issue 'Responses per second shows 0 response while it's not 0 #71 
-> It was a rounding issue where if you had a very low request/sec rate (something below 0.5), it would round it to 0.

2023-04-27 09:32 UTC, pmouawad commented on ulp-observability-front/src/main/front/src/app/components/ulp-observability-statistics/ulp-observability-statistics.component.ts
> +          ['avg','max','throughput'].forEach(type =>{
Use same approach also for total

2023-04-27 09:40 UTC, pmouawad commented on back/src/main/java/com/ubikloadpack/jmeter/ulp/observability/metric/ResponseResult.java
>       */
Javadocs missing

2023-04-27 12:24 UTC, pmouawad commented on back/src/main/java/com/ubikloadpack/jmeter/ulp/observability/registry/MicrometerRegistry.java
> +	private volatile Map<String, Pair<Long,Long>> startAndEndDatesOfSamplers = new ConcurrentHashMap<>();
volatile is useless

2023-04-28 08:22 UTC, pmouawad commented on back/src/main/java/com/ubikloadpack/jmeter/ulp/observability/registry/MicrometerRegistry.java
>  		String threadTag = Util.makeMicrometerName(result.getThreadGroupLabel());
threadTag is not useful

2023-04-28 08:22 UTC, pmouawad commented on back/src/main/java/com/ubikloadpack/jmeter/ulp/observability/registry/MicrometerRegistry.java
> +			this.registry.summary("summary.response", "sample", microMeterTag).record(result.getResponseTime());
for clarity can you rename registry to intervalRegistry
and totalReg to summaryRegistry 

Thanks

2023-04-28 08:29 UTC, pmouawad commented on back/src/main/java/com/ubikloadpack/jmeter/ulp/observability/registry/MicrometerRegistry.java
> +							.percentilePrecision(
Shouldn't you adjust bufferLength and expiry ? 
I guess that also setting minimumExpectedValue and maximumExpectedValue can be useful

2023-04-28 09:22 UTC, pmouawad requested changes
Thanks for PR @Liard-Thomas , I let you fix the remarks

2023-04-28 17:49 UTC, merged